spring:
  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  jpa:
    show-sql: true # JPA로 생성되는 쿼리 확인
    h2:
      console:
        enabled: true
        path: /h2-console # h2 db 웹 클라이언트 접속 url

logging:
  level:
    org.hibernate.type: trace  # JPA로 생성되는 쿼리의 파라미터 값 확인